<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adsongs-here all the fav songs</title>
    <link rel="stylesheet" href="procss.css">
    
</head>
<body>
    <nav>
        <ul>
            <li class="brand"><img src="local.jpg" alt="spotify">Adsongs</li>
            <li>Home</li>
            <li>About</li>
        </ul>
    </nav>
    <div class="container">
        
        <div class="songlist">
            <h1>Best of ADS-No Copyright Sound</h1>
            <div class="songitemcontainer">
            <div id="lo" class="songItem">
                <img src="adsong/ak1.jpg"alt="1" width="25px">
                <span class="songname"class="songname">So Many Things I Do</span>
                <span class="songlistplay"><span>5:34</span><i id="0" class="far songitemplay fa-1x fa-play-circle"></i></span>
            </div>
            <div id="lo" class="songItem">
                <img src="adsong/img2.jpg"alt="1">
                <span class="songname">So Many Things I Do</span>
                <span class="songlistplay"><span>5:34</span><i id="1"class="far songitemplay fa-1x fa-play-circle"></i></span>
            </div>
            <div id="lo" class="songItem">
                <img src="adsong/ak1.jpg"alt="1">
                <span class="songname">So Many Things I Do</span>
                <span class="songlistplay"><span>5:34</span><i id="2"class="far songitemplay fa-1x fa-play-circle"></i></span>
            </div>
            <div id="lo" class="songItem">
                <img src="adsong/img2.jpg"alt="1">
                <span class="songname">So Many Things I Do</span>
                <span class="songlistplay"><span>5:34</span><i id="3"class="far songitemplay fa-1x fa-play-circle"></i></span>
            </div>
            <div id="lo" class="songItem">
                <img src="adsong/ak1.jpg"alt="1">
                <span class="songname">So Many Things I Do</span>
                <span class="songlistplay"><span>5:34</span><i id="4" class="far songitemplay fa-1x fa-play-circle"></i></span>
            </div>
        </div>
    </div>
        <div class="songbanner">
            
        </div>
        <img src="babu.jpg"class="jk" alt="">
    </div>
    <div class="bottom">
        <input type="range" name="range" id="myprogressbar" value="0" min="0" max="100">
        <div class="icons">
            <i id="previous"class="fa-solid fa-3x fa-backward-step"></i></i></i>
            <i class="far fa-3x fa-play-circle"id="masterplay"></i>
            <i id="next"class="fa-solid fa-3x fa-forward-step"></i>
        </div>
        <div class="songinfo">
            <img class="paval" src="ad1.gif" id="gif">
            <div id="GO">Let me love you justin bieber</div>
        </div>
    </div>
    
    <script src="https://kit.fontawesome.com/32facea9ff.js" crossorigin="anonymous"></script>
    <script src="script.js"></script>
</body>
</html>
